name: proxy_actions
description: Flutter plugin for creating shortcuts on home screen, also known as
  proxy Actions on iOS and App Shortcuts on Android.
repository: https://github.com/flutter/plugins/tree/main/packages/proxy_actions/proxy_actions
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+proxy_actions%22
version: 1.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: proxy_actions_android
      ios:
        default_package: proxy_actions_ios
      macos:
        default_package: proxy_actions_macos

dependencies:
  flutter:
    sdk: flutter
  proxy_actions_android:
    path: ../proxy_actions_android/
  proxy_actions_ios:
    path: ../proxy_actions_ios/
  proxy_actions_macos:
    path: ../proxy_actions_macos/
  proxy_actions_platform_interface:
    path: ../proxy_actions_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
