name: proxy_actions_android
description: An implementation for the Android platform of the Flutter `proxy_actions` plugin.
repository: https://github.com/flutter/plugins/tree/main/packages/proxy_actions/proxy_actions_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+in_app_purchase%22
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: proxy_actions
    platforms:
      android:
        package: io.flutter.plugins.proxyactions
        pluginClass: ProxyActionsPlugin
        dartPluginClass: ProxyActionsAndroid

dependencies:
  flutter:
    sdk: flutter
  proxy_actions_platform_interface:
    path: ../proxy_actions_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
